name: CustomBuild

# Run this workflow whenever the build may be affected
on:
  workflow_dispatch:
  push:

jobs:
  build-firmware:
    runs-on: ubuntu-22.04
    container:
      image: infinitime/infinitime-build
    outputs:
      text_size: ${{ steps.output-sizes.outputs.text_size }}
      data_size: ${{ steps.output-sizes.outputs.data_size }}
      bss_size: ${{ steps.output-sizes.outputs.bss_size }}
    env:
      # InfiniTime sources are downloaded to the current directory.
      # Override SOURCES_DIR in build.sh
      SOURCES_DIR: .
    steps:
      - name: Checkout source files
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install resource build dependencies
        run:  |
          apt-get update
          apt-get -y install --no-install-recommends python3-pil
      - name: Build
        shell: bash
        run: /opt/build.sh all
      - name: Output build size
        id: output-sizes
        run: |
          . /opt/build.sh
          .github/workflows/getSize.sh "$BUILD_DIR"/src/pinetime-app-*.out >> $GITHUB_OUTPUT
      # Unzip the package because Upload Artifact will zip up the files
      - name: Unzip DFU package
        run: unzip ./build/output/pinetime-mcuboot-app-dfu-*.zip -d ./build/output/pinetime-mcuboot-app-dfu
      - name: Upload DFU artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime DFU ${{ github.head_ref }}
          path: ./build/output/pinetime-mcuboot-app-dfu/*
      - name: Upload MCUBoot image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime MCUBoot image ${{ github.head_ref }}
          path: ./build/output/pinetime-mcuboot-app-image-*.bin
      - name: Upload resources artifacts
        uses: actions/upload-artifact@v3
        with:
          name: InfiniTime resources ${{ github.head_ref }}
          path: ./build/output/infinitime-resources-*.zip